#This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        pip-flags: ['', '--editable']
        pydra:
        - 'git+https://github.com/effigies/pydra.git@fix/namespace#egg=pydra'
        - '--editable git+https://github.com/effigies/pydra.git@fix/namespace#egg=pydra'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install Pydra
      run: |
        pip install ${{ matrix.pydra }}
        python -c "import pydra as m; print(f'{m.__name__} {m.__version__} @ {m.__file__}')"
    - name: Install task package
      run: |
        pip install ${{ matrix.pip-flags }} ".[dev]"
        python -c "import pydra.tasks.TODO as m; print(f'{m.__name__} {m.__version__} @ {m.__file__}')"
        python -c "import pydra as m; print(f'{m.__name__} {m.__version__} @ {m.__file__}')"
    - name: Test with pytest
      run: |
        pytest -sv --doctest-modules pydra/tasks/TODO
